config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  put 'projects/:id/update_status', to: 'projects#update_status', as: 'update_project_status'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments, dependent: :destroy
  STATUSES = ['Not started', 'In progress', 'Completed'].freeze

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_project

  def create
    @comment = @project.comments.build(comment_params)
    if @comment.save
      redirect_to project_path(@project), notice: 'Comment was successfully created.'
    else
      render 'projects/show'
    end
  end

  def edit
    @comment = @project.comments.find(params[:id])
  end

  def update
    @comment = @project.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to project_path(@project), notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment = @project.comments.find(params[:id])
    @comment.destroy
    redirect_to project_path(@project), notice: 'Comment was successfully deleted.'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :update_status]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @comments = @project.comments
  end

  def index
    @projects = Project.all.includes(:comments)
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end


  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.body %> <%= link_to "Edit", edit_project_comment_path(comment.project, comment) %></p>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= form_with model: [@project, @comment], url: project_comment_path(@project, @comment), method: :patch do |form| %>
  <%= form.label :content %>
  <%= form.text_area :content %>

  <%= form.submit "Update Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversationHistory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_with model: @project, url: project_path(@project), method: :patch do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :status %>
  <%= form.select :status, options_for_select(Project::STATUSES, @project.status) %>

  <%= form.submit "Update Project" %>
<% end %>

app/views/projects/index.html.erb
<!-- app/views/projects/index.html.erb -->
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <h1>Projects</h1>

  <% @projects.each do |project| %>
    <div class="card mb-4">
      <%= link_to project_path(project) do %>
        <div class="card-body">
          <h4 class="card-title"><%= project.title %></h4>
          <% if project.status.present? %>
            <p>Status: <%= project.status.titleize %></p>
          <% end %>
          <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
  
  </div>

app/views/projects/new.html.erb
<div class="container">
  <h1>New Project</h1>

  <%= form_with model: @project, url: projects_path do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :status %>
      <%= form.select :status, options_for_select(Project::STATUSES.map { |s| [s.titleize, s] }), {}, class: "form-control" %>
      </div>

    <%= form.submit "Create Project", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<!-- app/views/projects/show.html.erb -->

<div class="container">
  <h1><%= @project.title %></h1>

  <div class="card mb-4">
    <div class="card-body">
      <% if @project.status.present? %>
        <p>Status: <%= @project.status.titleize %></p>
      <% end %>
    </div>
  </div>

  <h2>Comments</h2>

  <% @project.comments.each do |comment| %>
    <div class="card mb-4">
      <div class="card-body">
        <p class="card-text"><%= comment.body %></p>
        <p>Created at: <%= comment.created_at.strftime("%m/%d/%Y %I:%M %p") %></p>
      </div>
    </div>
  <% end %>

  <%= form_with model: [@project, Comment.new], local: true do |form| %>
    <div class="form-group">
      <%= form.label :body, "New comment" %>
      <%= form.text_area :body, rows: 4, class: "form-control" %>
    </div>

    <%= form.submit "Add Comment", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Back", projects_path, class: "btn btn-secondary" %>
  <%= link_to "update_status", edit_project_path(@project), class: "btn btn-secondary mr-2" %>

</div>